PythonWeb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from add_to_cart import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('home/', include('home.urls')),
                  path('', RedirectView.as_view(url='home/')),
                  path('product/', include('product.urls')),
                  path('add_to_cart/', include('add_to_cart.urls')),



              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='base'),
    path('register/', views.register, name='register'),
    path('login/', views.login_to, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.cart, name='cart'),

]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # path('add-product/', views.add_product, name='add-product'),

    # path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    # path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('add_product/', views.add_product, name='add_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('update_product/<int:product_id>/', views.update_product, name='update_product'),
    path('search/', views.search_pro, name='search'),
    path('product_list/', views.product_list, name='product_list'),
    path('product_by_filter/<int:category_id>/', views.product_by_category, name='product_by_category'),
   ]

home/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='images_product/')
    endow = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200)
    products = models.ManyToManyField(Product, related_name='categories', null=True, blank=True)

    def __str__(self) -> str:
        return self.name

home/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Tài Khoản', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Mật Khẩu', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Nhập lại mật khẩu', widget=forms.PasswordInput())

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError("Mật khẩu không hợp lệ")

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError("Tên tài khoản có chứ kí tự đặc biệt")
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản đã tồn tại")

    def save(self):
        User.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'],
                                 password=self.cleaned_data['password1'])

product/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
# Compare this snippet from PythonWeb/product/views.py:

home/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from add_to_cart.models import Cart
from product.models import Product
from .forms import RegistrationForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(request):
    products = Product.objects.all()
    products_endow = Product.objects.filter(endow=True)
    return render(request, 'home/index.html', {"products": products, "products_endow": products_endow})


def add_to_cart(request, product_id):
    # product = get_object_or_404(Product, pk=product_id)
    # cart, cart_created = Cart.objects.get_or_create(user=request.user)
    # cart_item, created = cart.cartitem_set.get_or_create(product=product, defaults={'quantity': 1})
    # if not created:
    #     cart_item.quantity += 1
    #     cart_item.save()
    # else:
    #     cart_item.quantity = 1
    #     cart_item.save()
    return redirect('home:base')


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:login')
    return render(request, 'home/register.html', {'form': form})


def login_to(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request=request, user=user)
            return redirect('home:base')

    return render(request, 'home/login.html')


def log_out(request):
    try:
        logout(request)
        return redirect('home:base')
    except Exception as e:
        return HttpResponse("ERROR")


def cart(request):
    return render(request, 'home/cart.html')

product/views.py
from django.shortcuts import redirect, render
from .forms import ProductForm
from .models import *


# Create your views here.
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home:base')
        else:
            return redirect('product:add_product')
    else:
        form = ProductForm()
        return render(request, 'product/add_product.html', {'form': form})


def delete_product(request, product_id):
    product = Product.objects.get(id=product_id)
    product.delete()
    return redirect('home:base')


def update_product(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('home:base')
        else:
            return redirect('product:update_product', product_id=product_id)
    else:
        form = ProductForm(instance=product)
        return render(request, 'product/update_product.html', {'form': form})


def search_pro(request):
    if request.method == 'GET':
        search = request.GET.get('search')
        products = Product.objects.filter(name__icontains=search)
        # Filter the products by name insensitive case

        return render(request, 'home/search_product.html', {'products': products})
    else:
        return redirect('home:base')


def product_list(request):
    products = Product.objects.all().order_by('-id')
    return render(request, 'product/product_list.html', {'products': products})


def product_by_category(request, category_id):
    category = Category.objects.get(id=category_id)
    products = category.products.all()
    return render(request, 'product/product_list.html', {'products': products})

home/templates/home/_slider.html
{% load static %}

<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/fishslider1.jpg' %}" class="d-block w-100" alt="..." />
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/fishslider2.jpg' %}" class="d-block w-100" alt="..." />
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/fishslider3.jpg' %}" class="d-block w-100" alt="..." />
      </div>
    </div>
  </div>

home/templates/home/endow.html
{% load static %}
<link rel="stylesheet" href="{% static 'product/fonts/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'product/Pretty-Product-List-.css' %}">
<link rel="stylesheet" href="{% static 'product/Pretty-Product-Grid-images.css' %}">


<div class="container my-5">
    <h1 class="text-center mb-4">Endow List</h1>
    <div class="row">
        <!-- Replace with your actual product data -->

        {#      <div class="col-md-6 col-lg-4 mb-4">#}
        {#        <div class="card">#}
        {#          <img src="{{ product.image.url }}" class="card-img-top" alt="Product Image">#}
        {#          <div class="card-body">#}
        {#            <h5 class="card-title">{{ product.name }}</h5>#}
        {#            <p class="card-text">{{ product.description }}</p>#}
        {#            <p class="card-text font-weight-bold">{{ product.price }}</p>#}
        {#            <a href="{% url "home:add-to-cart" product_id=product.id %}" class="btn btn-primary">Add to Cart</a>#}
        {#          </div>#}
        {#        </div>#}
        {#      </div>#}
{#        {% include 'product/index.html' with product=product %}#}
        <!-- Repeat the above code for each product -->
    </div>

    <div class="row product-list">
        {% for product in products %}
            <div class="col-sm-6 col-md-4 product-item">
                <div class="product-container">
                    <div class="row">
                        <div class="col-md-12"><a class="product-image" href="#"><img
                                src="{{ product.image.url }}"></a></div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <h2><a href="#">{{ product.name }}</a></h2>
                        </div>
                        <div class="col-4"><a class="small-text" href="#">compare </a></div>
                    </div>
                    <div class="product-rating"><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                            class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i><a
                            class="small-text" href="#">82 reviews</a></div>
                    <div class="row">
                        <div class="col-12">
                            <p class="product-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam
                                ornare sem sed nisl dignissim, facilisis dapibus lacus vulputate. Sed lacinia lacinia
                                magna. </p>
                            <div class="row">
                                <div class="col-6">
                                    <button class="btn btn-light" type="button">Buy Now!</button>
                                </div>
                                <div class="col-6">
                                    <p class="product-price">{{ product.price }} </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

</div>

home/templates/home/index.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}


{% block content %}
    {% include 'home/_slider.html' %}
    {% include "home/products.html" with products=products %}
    
    {% if user.is_superuser %}
        <div class="button_add_product mx-auto"
             style="background-color: darkgray;width: 100px;text-align: center;border-radius: 3px ">
            <a href="{% url "product:add_product" %}" style="text-decoration: none;">Add Product</a>
        </div>
    {% endif %}


    {% include 'home/introduce.html' %}
{% endblock %}

home/templates/home/introduce.html
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Untitled</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich">
    <link rel="stylesheet" href="static/css/Articles-Cards-images.css">
    <link rel="stylesheet" href="static/css/Features-Centered-Icons-icons.css">
    <link rel="stylesheet" href="static/css/Simple-Header-y-Navbar-adaptativo-nav.css">
    <link rel="stylesheet" href="static/css/Simple-Header-y-Navbar-adaptativo.css">
</head>

<body>
    <footer class="text-white bg-dark"></footer>
    <div class="container py-4 py-xl-5">
        <div class="row mb-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2>GIỚI THIỆU</h2>
                <p class="w-lg-50">DH Store là một cửa hàng buôn bán đồ gia dụng.Cam kết hàng chất lượng cao và đổi trả trong vòng 3 ngày </p>
            </div>
        </div>
        <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-xl-3">
            <div class="col">
                <div class="card"><img class="card-img-top w-100 d-block fit-cover" style="height: 200px;" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png">
                    <div class="card-body p-4">
                        <p class="text-primary card-text mb-0">Article</p>
                        <h4 class="card-title">Lorem libero donec</h4>
                        <p class="card-text">Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.</p>
                        <div class="d-flex"><img class="rounded-circle flex-shrink-0 me-3 fit-cover" width="50" height="50" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png">
                            <div>
                                <p class="fw-bold mb-0">John Smith</p>
                                <p class="text-muted mb-0">Erat netus</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card"><img class="card-img-top w-100 d-block fit-cover" style="height: 200px;" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png">
                    <div class="card-body p-4">
                        <p class="text-primary card-text mb-0">Article</p>
                        <h4 class="card-title">Lorem libero donec</h4>
                        <p class="card-text">Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.</p>
                        <div class="d-flex"><img class="rounded-circle flex-shrink-0 me-3 fit-cover" width="50" height="50" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png">
                            <div>
                                <p class="fw-bold mb-0">John Smith</p>
                                <p class="text-muted mb-0">Erat netus</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card"><img class="card-img-top w-100 d-block fit-cover" style="height: 200px;" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png">
                    <div class="card-body p-4">
                        <p class="text-primary card-text mb-0">Article</p>
                        <h4 class="card-title">Lorem libero donec</h4>
                        <p class="card-text">Nullam id dolor id nibh ultricies vehicula ut id elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus.</p>
                        <div class="d-flex"><img class="rounded-circle flex-shrink-0 me-3 fit-cover" width="50" height="50" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png">
                            <div>
                                <p class="fw-bold mb-0">John Smith</p>
                                <p class="text-muted mb-0">Erat netus</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

home/templates/home/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{%static 'css/login.css'%}">
</head>
<body>
    <div class="container"> 
        <h2>LOGIN</h2>
    <form method="post" >
        {% csrf_token %}
        <input type="text" name="username" id="">
        <input type="password" name="password" id="">
        <input type="submit"  value='ĐĂNG NHẬP'></input>
      
    </form>
    <p>Don't have an account? <a href="{% url "home:register" %}">Sign up</a></p>
</div>
</body>
</html>

home/templates/home/products.html
{% load static %}
<link rel="stylesheet" href="{% static 'product/fonts/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'product/Pretty-Product-List-.css' %}">
<link rel="stylesheet" href="{% static 'product/Pretty-Product-Grid-images.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<div class="container my-5">
    <h1 class="text-center mb-4">Product List</h1>
    <div class="row">


    </div>

    <div class="row product-list">


        {% for product in products %}
            <div class="col-sm-6 col-md-4 product-item">
                <div class="product-container">
                    <div class="row">
                        <div class="col-md-12"><a class="product-image" href="#"><img
                                src="{{ product.image.url }}"></a></div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <h2><a href="#">{{ product.name }}</a></h2>
                        </div>
                        <div class="col-4"><a class="small-text" href="#">compare </a></div>
                    </div>
                    <div class="product-rating"><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                            class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i><a
                            class="small-text" href="#">82 reviews</a></div>
                    <div class="row">
                        <div class="col-12">
                            <p class="product-description">{{ product.description }} </p>
                            <div class="row">
                                <div class="col-6">

                                    <a href="#" class="add-to-cart btn btn-light"data-toast-target="#liveToast-{{ product.id }}"
                                       data-product-id="{{ product.id }}">
                                        Buy Now!
                                    </a>
                                    <div class="toast-container position-fixed bottom-0 start-0 p-6">
                                        <div class="toast" id="liveToast-{{ product.id }}" role="alert"
                                             aria-live="assertive" aria-atomic="true">
                                            <div class="toast-body">
                                                <div class="d-flex gap-4">
                                                    <span><i
                                                            class="fa-solid fa-circle-check fa-lg icon-success"></i></span>
                                                    <div class="d-flex flex-column flex-grow-1 gap-2">
                                                        <div class="d-flex align-items-center">
                                                            <span class="fw-semibold">{{ product.name }} added to cart</span>
                                                            <button type="button" class="btn-close btn-close-sm ms-auto"
                                                                    data-bs-dismiss="toast" aria-label="Close"></button>
                                                        </div>
                                                        <span>I will auto dismiss after 8 seconds.</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                                <div class="col-6">
                                    <p class="product-price">{{ product.price }} </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>

</div>


<script>

    document.querySelectorAll('[data-toast-target]').forEach(button => {
        button.addEventListener('click', () => {
            const toastElement = document.getElementById(button.dataset.toastTarget.slice(1));
            const toast = new bootstrap.Toast(toastElement);
            toast.show();
        });
    });

</script>


<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'product/js/bs-init.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $(".add-to-cart").click(function (e) {
            e.preventDefault();
            var product_id = $(this).data("product-id");
            console.log(product_id);
            $.ajax({
                url: `http://127.0.0.1:8000/add_to_cart/ajax/add_to_cart/${product_id}/`,
                data: {
                    'product_id': product_id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                type: 'POST',
                dataType: 'json',
                success: function (data) {
                    if (data.success) {
                        // Update the cart on the page
                        {#$(".hidden").className = "block";#}
                        console.log("SUCCESS")
                        {#${'#toastAddToCart'}.toast('show');#}
                    }
                }
            });
        });
    });
</script>

home/templates/home/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
</head>
<body>
<div style="text-align: center;">
    <form method='POST' class="formedit">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value='Đăng kí'/>
        <p>Already have an account? <a href="{% url "home:login" %}">Sign in</a></p>
    </form>
</div>
</body>
</html>

home/templates/home/search_product.html
{% extends 'base.html' %}

{% block title %}
	Product List
{% endblock %}


{% block content %} 
{% load static %}
<link rel="stylesheet" href="{% static 'product/fonts/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'product/Pretty-Product-List-.css' %}">
<link rel="stylesheet" href="{% static 'product/Pretty-Product-Grid-images.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<div class="row product-list">
    
    
        {% for product in products %}
            <div class="col-sm-6 col-md-4 product-item">
                <div class="product-container">
                    <div class="row">
                        <div class="col-md-12"><a class="product-image" href="#"><img
                                src="{{ product.image.url }}"></a></div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <h2><a href="#">{{ product.name }}</a></h2>
                        </div>
                        <div class="col-4"><a class="small-text" href="#">compare </a></div>
                    </div>
                    <div class="product-rating"><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                            class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i><a
                            class="small-text" href="#">82 reviews</a></div>
                    <div class="row">
                        <div class="col-12">
                            <p class="product-description">{{ product.description }} </p>
                            <div class="row">
                                <div class="col-6">

                                    <a href="#" class="add-to-cart btn btn-light toast-trigger " id="liveToastBtn"
                                       data-product-id="{{ product.id }}">
                                        Buy Now!
                                    </a>

                                    <div class="toast-container position-fixed bottom-0 end-0 p-3">
                                        <div class="toast text-bg-primary border-0 align-items-center hide" role="alert"
                                             data-bs-animation="false" id="liveToast" aria-live="assertive"
                                             aria-atomic="true">
                                            <div class="d-flex">
                                                <div class="toast-body">
                                                    <span> Hello, world! This is a toast message. </span></div>
                                                <button class="btn-close m-auto btn-close-white me-2" type="button"
                                                        data-bs-dismiss="toast" aria-label="Close"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <script>
                                        const toastTrigger = document.getElementById('liveToastBtn')
                                        const toastLiveExample = document.getElementById('liveToast')
                                        console.log('dljvnlzdgklfxnkl')
                                        if (toastTrigger) {
                                            toastTrigger.addEventListener('click', () => {
                                                const toast = new bootstrap.Toast(toastLiveExample)

                                                toast.show()
                                            })
                                        }
                                    </script>
                                    {#                                    <div>#}
                                    {#                                        <button class="btn btn-primary" type="button" id="liveToastBtn">Show live#}
                                    {#                                            toast#}
                                    {#                                        </button>#}
                                    {#                                        <div class="toast-container position-fixed bottom-0 end-0 p-3">#}
                                    {#                                            <div class="toast text-bg-primary border-0 align-items-center hide"#}
                                    {#                                                 role="alert" data-bs-animation="false" id="liveToast"#}
                                    {#                                                 aria-live="assertive" aria-atomic="true">#}
                                    {#                                                <div class="d-flex">#}
                                    {#                                                    <div class="toast-body"><span> Hello, world! This is a toast message. </span>#}
                                    {#                                                    </div>#}
                                    {#                                                    <button class="btn-close m-auto btn-close-white me-2" type="button"#}
                                    {#                                                            data-bs-dismiss="toast" aria-label="Close"></button>#}
                                    {#                                                </div>#}
                                    {#                                            </div>#}
                                    {#                                        </div>#}
                                    {#                                        <script>#}
                                    {#                                            const toastTrigger = document.getElementById('liveToastBtn')#}
                                    {#                                            const toastLiveExample = document.getElementById('liveToast')#}
                                    {#                                            if (toastTrigger) {#}
                                    {#                                                toastTrigger.addEventListener('click', () => {#}
                                    {#                                                    const toast = new bootstrap.Toast(toastLiveExample)#}
                                    {##}
                                    {#                                                    toast.show()#}
                                    {#                                                })#}
                                    {#                                            }#}
                                    {#                                        </script>#}
                                    {#                                    </div>#}

                                </div>
                                <div class="col-6">
                                    <p class="product-price">{{ product.price }} </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>
{% endblock %}