PythonWeb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from add_to_cart import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('home/', include('home.urls')),
                  path('', RedirectView.as_view(url='home/')),
                  path('product/', include('product.urls')),
                  path('add_to_cart/', include('add_to_cart.urls')),



              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

add_to_cart/urls.py
from django.urls import path
from . import views
app_name = 'add_to_cart'
urlpatterns = [
    # ... other urls ...
    # path('purchased_products/', views.purchased_products, name='purchased_products'),
    # path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('ajax/add_to_cart/<int:product_id>/', views.ajax_add_to_cart, name='ajax_add_to_cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('view_cart/', views.view_cart, name='view_cart'),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='base'),
    path('register/', views.register, name='register'),
    path('login/', views.login_to, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.cart, name='cart'),

]

add_to_cart/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings

from product.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    purchase_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.product.name

add_to_cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

from django.shortcuts import render
# Create your views here.
from django.shortcuts import render, redirect
from .models import *
from product.models import Product
from django.shortcuts import get_object_or_404


# def add_to_cart(request, product_id):
#     product = Product.objects.get(pk=product_id)
#     cart, cart_created = Cart.objects.get_or_create(user=request.user)
#     cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
#     if not created:
#         cart_item.quantity += 1
#         cart_item.save()
#     else:
#         cart_item.quantity = 1
#         cart_item.save()
#
#     return redirect('home:base')


def ajax_add_to_cart(request, product_id):
    print('ajax_add_to_cart')
    product = Product.objects.get(pk=product_id)
    cart, _ = Cart.objects.get_or_create(user=request.user)

    # cart_items, created = cart.cartitem_set.get_or_create(product=product, defaults={'quantity': 1})
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)

    if not created:
        cart_item.quantity += 1
        cart_item.save()
    else:
        cart_item.quantity = 1
        cart_item.save()

    return JsonResponse({'success': True})


def delete_from_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart = Cart.objects.get(user=request.user)

    cart_item = CartItem.objects.get(cart=cart, product=product)
    cart_item.delete()

    return redirect('add_to_cart:view_cart')


def view_cart(request):
    cart, _ = Cart.objects.get_or_create(user=request.user)
    cart_items = CartItem.objects.filter(cart=cart)
    # total price products in cart
    total_price = 0
    for item in cart_items:
        total_price += item.product.price * item.quantity

    return render(request, 'add_to_cart/purchased_products.html',
                  {'cart_items': cart_items, 'total_price': total_price})

add_to_cart/templates/add_to_cart/purchased_products.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Cart
{% endblock %}
{% block content %}
    <div class="shopping-cart">
        <div class="px-4 px-lg-0">

            <div class="pb-5">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">

                            <!-- Shopping cart table -->
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="p-2 px-3 text-uppercase">Product</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Price</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Quantity</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Remove</div>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for cart_item in cart_items %}
                                        <tr>
                                            <th scope="row" class="border-0">
                                                <div class="p-2">
                                                    <img src="{{ cart_item.product.image.url }}"
                                                         alt="" width="70" class="img-fluid rounded shadow-sm">
                                                    <div class="ml-3 d-inline-block align-middle">
                                                        <h5 class="mb-0"><a href="#"
                                                                            class="text-dark d-inline-block align-middle">
                                                            <strong>{{ cart_item.product.name }}</strong>
                                                        </a></h5><span
                                                            class="text-muted font-weight-normal font-italic d-block">Category: Watches</span>
                                                    </div>
                                                </div>
                                            </th>
                                            <td class="border-0 align-middle">
                                                <strong> {{ cart_item.product.price }}</strong></td>

                                            <td class="border-0 align-middle"><strong> <label>
                                                <input type="number"
                                                       value="{{ cart_item.quantity }}" />

                                            </label></strong>
                                            </td>
                                            <td class="border-0 align-middle" >
                                                <a class="btn btn-danger" href="{% url 'add_to_cart:delete_from_cart' cart_item.product.id %}" style="text-decoration: none;">
                                                    Delete
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                            <!-- End -->
                        </div>
                    </div>

                    <div class="row py-5 p-4 bg-white rounded shadow-sm">
                        <div class="col-lg-6">
                            <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Coupon code
                            </div>
                            <div class="p-4">
                                <p class="font-italic mb-4">If you have a coupon code, please enter it in the box
                                    below</p>
                                <div class="input-group mb-4 border rounded-pill p-2">
                                    <input type="text" placeholder="Apply coupon" aria-describedby="button-addon3"
                                           class="form-control border-0">
                                    <div class="input-group-append border-0">
                                        <button id="button-addon3" type="button" class="btn btn-dark px-4 rounded-pill">
                                            <i class="fa fa-gift mr-2"></i>Apply coupon
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Instructions
                                for seller
                            </div>
                            <div class="p-4">
                                <p class="font-italic mb-4">If you have some information for the seller you can leave
                                    them in the box below</p>
                                <textarea name="" cols="30" rows="2" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Order summary
                            </div>
                            <div class="p-4">
                                <p class="font-italic mb-4">Shipping and additional costs are calculated based on values
                                    you have entered.</p>
                                <ul class="list-unstyled mb-4">


                                    <li class="d-flex justify-content-between py-3 border-bottom"><strong
                                            class="text-muted">Total</strong>
                                        <h5 class="font-weight-bold">{{ total_price }}</h5>
                                    </li>
                                </ul>
                                <a href="#" class="btn btn-dark rounded-pill py-2 btn-block">Procceed to checkout</a>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
{% endblock content %}